name = "OPF"
uuid = "e5a60484-4a5d-11e9-2a08-272f2390f1e9"
authors = ["Jake Roth <jmroth@uchicago.edu>"]
version = "0.1.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
JuMPUtil = "424dbc2a-5984-526e-a872-204593702e55"
MPCCases = "18da711e-460b-11e9-09d1-c9dc5c0ea288"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
